GET http://localhost:5000/api/test

###
POST http://localhost:5000/api/auth/signup
Content-Type: application/json

{
    "username": "bob2",
    "email": "bob2@gmail.com",
    "password": "123456789"
}
###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "kenny@gmail.com",
    "password": "123"
}

###
GET http://localhost:5000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YmE4YTJmZWVmNTI4MWU5ZDAyOGFiMSIsImVtYWlsIjoia2VubnlAZ21haWwuY29tIiwiaWF0IjoxNzU3NDA3MTIzLCJleHAiOjE3NTc0MTA3MjN9.hzNvx5bPeDyMVsxPFbOldXD5_v4fC8eCx6nLT7rbkfs


###
POST http://localhost:5000/api/books
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YmE4YTJmZWVmNTI4MWU5ZDAyOGFiMSIsImVtYWlsIjoia2VubnlAZ21haWwuY29tIiwiaWF0IjoxNzU3NDA3MTIzLCJleHAiOjE3NTc0MTA3MjN9.hzNvx5bPeDyMVsxPFbOldXD5_v4fC8eCx6nLT7rbkfs

{
  "title": "Javascript 2",
  "author": "Robert Bob",
  "description": "Un classique sur les bonnes pratiques"
}

###
GET http://localhost:5000/api/books
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YmE4YTJmZWVmNTI4MWU5ZDAyOGFiMSIsImVtYWlsIjoia2VubnlAZ21haWwuY29tIiwiaWF0IjoxNzU3NDA3MTIzLCJleHAiOjE3NTc0MTA3MjN9.hzNvx5bPeDyMVsxPFbOldXD5_v4fC8eCx6nLT7rbkfs
